### ISSUE TITLE
[as2_python_api] resume() blocks until behavior is finished

### ISSUE THREAD

**Issue by javilinos** [aerostack2/aerostack2#104]
### ROS2 Version

humble

### Version

main

### What happened?

Uppon calling resume function of stopped behavior, behavior resumes its task successfully but it blocks until behavior finishes its task, so it cannot be stopped again. No error log is returned.

**Comment by pariaspe** [comment]
Hi @javilinos , resuming can be done blocking or not:
```python
    def resume(self, wait_result: bool = True) -> bool:
        """Continue with current behavior

        :param wait_result: wait to behavior end, defaults to True
        :return: resume succeed or not
        """
```

**Comment by javilinos** [comment]
Tested and works fine, thanks.
