### ISSUE TITLE
[aerial_platform] Review some attributes accessibility

### ISSUE THREAD

**Issue by pariaspe** [aerostack2/aerostack2#120]
- `cmd_freq_` and `info_freq_` attributes should be private?
- `platform_info_msg_` should be only readable? 
https://github.com/aerostack2/aerostack2/blob/af0598f44ef1c483c34771411711c7da97c23678/as2_core/include/as2_core/aerial_platform.hpp#L84-L91

What do you think @miferco97 ?

**Comment by miferco97** [comment]
if they are not used in other platforms it could be moved to private, but i think we can mantain them protected in order to allow developers to handle them.
