### ISSUE TITLE
[as2_core] AerialPlatform support to config files describing sensors list

### ISSUE THREAD

**Issue by pariaspe** [aerostack2/aerostack2#167]
Manage platform sensor from a config file where a sensor and its pose is defined. The AeriaPlatform should create its own sensors based on the given config file.
Then, there could be available different configuration for the same platform.

**Comment by RPS98** [comment]
In as2_core Sensor, when instantiating the object, its transformation relative to base_link can be set. 
Therefore, the node (platform or hardware interface) is in charge of setting this transformation.
Some sensors, like cameras, already use configuration files for this
