### ISSUE TITLE
[as2_behaviors_motion] Follow Reference Behavior Transforms Error

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#196]
### ROS2 Version

humble

### Version

main

## Description

When launch motion_behaviors_launch, follow reference behavior displays the text on the screen: "Could not get state from frame earth to the desired frame"

Also, follow reference behavior should not be in motion_behaviors_launch, and only launch it with its launcher.

## Reproduce the error

Using project ignition, launch simulation and main launcher, and see the behavior screen output.

**Comment by javilinos** [comment]
Hi @RPS98, there was a redundant-missplaced warning which should be indeed caught by the exception, it is now fixed.

**Comment by RPS98** [comment]
The problem is that this sentence is call every twist state callback

https://github.com/aerostack2/aerostack2/blob/298fdfa92fbc4cb3cf70b24b50e52272e23a3a49/as2_behaviors/as2_behaviors_motion/follow_reference_behavior/include/follow_reference_behavior/follow_reference_behavior.hpp#L265
