### ISSUE TITLE
[as2_simulation_assets] battery sensor loading 

### ISSUE THREAD

**Issue by javilinos** [aerostack2/aerostack2#204]
### ROS2 Version

humble

### Version

main

### What happened?

* Battery should be loaded as a sensor in the payload section within the simulation configuration file. 
* Platform crash when setting flight_time as float value. It should be casted to an integer value.

**Comment by RPS98** [comment]
@javilinos can we close it?

**Comment by RPS98** [comment]
Done in  #556
