### ISSUE TITLE
[as2_simulation_assets] earth needs to be alligned in ENU frame 

### ISSUE THREAD

**Issue by javilinos** [aerostack2/aerostack2#229]
### ROS2 Version

humble

### Version

main

### What happened?

Earth is not alligned in ENU frame, this means that the North is aligned with the X axis of earth, the Y axis of earth is alligned with the West.

**Comment by miferco97** [comment]
Which commit solves this ?

**Comment by javilinos** [comment]
Done in Pull Request #231 , however there is a file that modifies ground_truth plugin to add gps support that will be removed from that pull request and moved to branch #230-add_gps_support_from_ground_truth_plugin. Will keep this open until merged #231 is merged.
