### ISSUE TITLE
[as2_platform_dji] Move from DJI-OSDK to DJI-PSDK 

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#248]
### Feature Description

New aircraft uses DJI PSDK instead of OSDK. Develop a platform to support PSDK

**Comment by RPS98** [comment]
Should we first add the DJI PSDK to aerostack2 @miferco97 ?

**Comment by pariaspe** [comment]
https://github.com/aerostack2/as2_platform_dji_psdk
