### ISSUE TITLE
[as2_belief_memory] Belief memory in ROS2

### ISSUE THREAD

**Issue by javilinos** [aerostack2/aerostack2#255]
### Feature Description

Adapt and maybe improve the already implemented belief memory from AS1 to AS2.

### Implementation Considerations

- Every step that takes to adapt a node from ROS 1 to ROS 2.
- Make it swarm oriented.

**Comment by miferco97** [comment]
Some other knowledge sharing and methods should be discussed, such as knowledge graphs. PDDL is other option to consired. 
We should also check this https://plansys2.github.io/, and see if it has any sense to use this inside as2

**Comment by miferco97** [comment]
I will close this issue as it is not planned to continue with this idea.
