### ISSUE TITLE
[AS2 IMAGES] Create Images for RPi, nvidia, or even ubuntu that has all the necessary inside and compiled.

### ISSUE THREAD

**Issue by miferco97** [aerostack2/aerostack2#265]
### Feature Description

Creating .iso images for the companion computers that we use could be a nice option for easing the setup of Aerostack2 in the different computers. 

### Implementation Considerations

In a sense this can be similar to create docker images, but for companion computers this could be super convient for setting up new computers or  drones and don't worry about compiling.

**Comment by pariaspe** [comment]
@miferco97 still interested in this?

**Comment by miferco97** [comment]
I think that at this moment we can continue with docker images, rather than creating images that are difficult to update and maintain
