### ISSUE TITLE
[Gazebo project] Looks project missed PySimpleGUI python dependency

### ISSUE THREAD

**Issue by drfenixion** [aerostack2/aerostack2#287]
### ROS2 Version

humble

### Version

main

### What happened?

When i run `./launch_as2.bash -t` (gazebo project) i get only gazebo and main terminal. I did not get Keyboard Teleoperation.
I make some investigation of broblem and source of it is missed PySimpleGUI dependency (i dont see any installation of this in project). After manual install it works.
Looks you should add it to package.xml somethere.

P.S. I want to use your project but documentation looks abandoned. Please focus on documentation. Fill empty entities and add more examples how i can write my project based on aerostack2. It will awesome if examples in python.

**Comment by RPS98** [comment]
@javilinos Has this issue been resolved already?
