### ISSUE TITLE
[Gazebo project] as2_behavior_tree_main-1 ERROR

### ISSUE THREAD

**Issue by drfenixion** [aerostack2/aerostack2#288]
### ROS2 Version

humble

### Version

main

### What happened?

When i run `./launch_as2.bash -b` in Gazebo project, I get error:

```
[INFO] [as2_behavior_tree_main-1]: process started with pid [3741]
[as2_behavior_tree_main-1] [ERROR] [1687087606.296221559] [drone0.bt_manager]: "TakeOffBehavior" action server not available after waiting for 1 s
[as2_behavior_tree_main-1] terminate called after throwing an instance of 'std::length_error'
[as2_behavior_tree_main-1]   what():  basic_string::_M_create
[ERROR] [as2_behavior_tree_main-1]: process has died [pid 3741, exit code -6, cmd '/home/ubuntu/ros2/aerostack2_ws/install/as2_behavior_tree/lib/as2_behavior_tree/as2_behavior_tree_main --ros-args -r __ns:=/drone0 --params-file /tmp/launch_params_21ibjgk7'].
```

I use my own docker image (with your install instructions) based on tiryoh/ros2-desktop-vnc:humble 

![2](https://github.com/aerostack2/aerostack2/assets/13005708/9a941bf4-2162-4404-a7e6-490ee1eb5b26)

Second start after stop is ok. Looks It can be fixed by adding more wait time TakeOffBehavior action server before throw error.
![3](https://github.com/aerostack2/aerostack2/assets/13005708/6f89998f-fca1-42e4-bd83-896f70e8053b)

But when i run `python3 mission_behavior_tree.py` dron does nothing and script ends instantly.
![4](https://github.com/aerostack2/aerostack2/assets/13005708/9e224d5f-86f0-40eb-882b-cf3fae521a41)

I understood reason of this empty end of `python3 mission_behavior_tree.py`, finally. It does not work without -t (keyboard teleoperation). You should add automatic start keyboard teleoperation when only -b key present.
I mean `./launch_as2.bash -b` does not work now and `./launch_as2.bash -b -t `works.
![5](https://github.com/aerostack2/aerostack2/assets/13005708/5a9d198b-d963-442b-a7e3-087dbf7375de)

**Comment by pariaspe** [comment]
Hi @drfenixion, I've just tested it and I'm not able to reproduce your error. I don't need to add more time to the Takeoff action neither launch it with `-t` option. 
Could please extend the information about your system?

**Comment by drfenixion** [comment]
Tried `ros2 topic pub /drone0/start std_msgs/msg/String "data: ''"` 5 times with and without -t. All times it works fine.

**Comment by pariaspe** [comment]
No error on gazebo window neither? Spawn problems usually come from zombie processes in the background. Check if some gazebo bridges or similar did not die properly.
