### ISSUE TITLE
[ALL] improvement of install dependencies system 

### ISSUE THREAD

**Issue by drfenixion** [aerostack2/aerostack2#289]
### Feature Description

I see you have doubled dependency install system. Maybe one of them was inherited from old version. Looks it need to remove bash install and save only package.xml install.

Example:
as2_behavior_tree/install_bt_dependencies.bash
```
#!/bin/bash

sudo apt-get update
sudo apt-get install ros-$ROS_DISTRO-behaviortree-cpp-v3 -y 
sudo apt-get install ros-$ROS_DISTRO-nav2-msgs -y 
sudo apt-get install ros-$ROS_DISTRO-nav2-behavior-tree -y 
```
as2_behavior_tree/package.xml
```
<depend>behaviortree_cpp_v3</depend>
<depend>nav2_behavior_tree</depend>
<depend>nav2_msgs</depend>
```

Doubled install system confuses developers and consist of a lot of useless code.

**Comment by drfenixion** [comment]
It is not only end bash script. It is also starting install script aerostack2_ws/src/aerostack2/installers/install_package_dependencies.py

And starting script also uses in your dockerfile 
aerostack2_ws/src/aerostack2/docker/Dockerfile
`RUN /bin/bash -c 'python3 installers/install_package_dependencies.py --repos ./installers/as2_rolling.repos -p .'`

**Comment by pariaspe** [comment]
`installers` folder is quite old too. We might delete it soon, what do you think @miferco97 ?
Also, docker is work in progress, latest changes are 6 months ago. It will be great if you could open a PR with your dockerfile. Thanks!

**Comment by drfenixion** [comment]
> `installers` folder is quite old too. We might delete it soon, what do you think @miferco97 ? Also, docker is work in progress, latest changes are 6 months ago. It will be great if you could open a PR with your dockerfile. Thanks!

Do you ask my dockerfile?

**Comment by pariaspe** [comment]
Yes, you are building a docker image, right?

**Comment by drfenixion** [comment]
> Yes, you are building a docker image, right?

Yes, I do. I will make PR.

**Comment by drfenixion** [comment]
Added PR with docker
https://github.com/aerostack2/aerostack2/pull/294

**Comment by pariaspe** [comment]
Thanks!
