### ISSUE TITLE
[project_gazebo] Change to Hexrotor 

### ISSUE THREAD

**Issue by Pelope9832** [aerostack2/aerostack2#319]
### ROS2 Version

humble

### Version

main

### What happened?

Hello! I've been trying out Aerostack 2 for a few days, and I've attempted to test the hexrotor model by changing the world.json in the example project_gazebo, but it's not working. Is this an error, or do I need to change something else in the configuration? Thank you very much.

### Relevant log output

```shell
[as_motion_controller_node-1] [ERROR] [1692861206.110486892] [drone0.controller_manager]: Failed to convert command twist to output frame, from drone0/odom to drone0/base_link.
```

**Comment by pariaspe** [comment]
Hi @Pelope9832, thanks for reporting the bug. It should be fixed in #321, feel free to try it out.
