### ISSUE TITLE
[as2_python_api] modules outside python api cannot be loaded in mission Interpreter

### ISSUE THREAD

**Issue by javilinos** [aerostack2/aerostack2#333]
### ROS2 Version

humble

### Version

main

### What happened?

Modules located outside of as2_python_api cannot be loaded into the mission interpreter, as this automatically append the as2_python_api path into the module name within the function load_module().

**Comment by RPS98** [comment]
@javilinos Has this issue been resolved already?

**Comment by javilinos** [comment]
Merge #344 and it will be solved
