### ISSUE TITLE
Where should be installed? There is any obstacle avoidance implemented?

### ISSUE THREAD

**Issue by Cristian-wp** [aerostack2/aerostack2#343]
Hello, sorry for the dummy questions but I have not understand this two points...

1. The stack must be installed on a companion computer and the waypoint are sended to a Pixhawk(with PX4 firmware)?
2. There is any obstacle avoidance or collision detection provided?

Thanks in advance.

**Comment by pariaspe** [comment]
Hi @Cristian-wp ,
1. Aerostack2 can be installed on a onboard computer or ground computer, depending on the system you have. On PX4 we usually install it onboard. You can mainly command a PX4 with waypoints (XYZ local coordinates), with speed references or by sending trajectories.
2. No, there is not an obstacle avoidance provided yet. We are currently working on it but it is work in progress only.
