### ISSUE TITLE
[as2_pkg] Webots Simulation

### ISSUE THREAD

**Issue by matthew-william-lock** [aerostack2/aerostack2#345]
### Feature Description

Hey, I am wondering if there are any plans to feature other simulators aside from Gazebo? I am working with the Crazyflie drones and there are currently no well-supported frameworks that I can find. The Crazyflie has recently been added to Webots as a natively supported platform and was wondering if there were any plans to potentially include Webots as a sim platform in as2?

Cheers!

**Comment by pariaspe** [comment]
Hi @matthew-william-lock , it's not in the short term roadmap. We have explored in the past crazyflie sdf models for gazebo but the flight was unstable. We will be glad to help external contributors working on stuff like this.
