### ISSUE TITLE
[as2_behaviors_platform] Behaviors return False even when they succeed in the action

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#378]
### ROS2 Version

humble

### Version

main

### What happened?

When calling platform behaviors using the `as2_python_api`, action calls always return False, even when the action, such as Take Off or Land, has been successfully done.

**Comment by miferco97** [comment]
@pariaspe @RPS98 is this solved?

**Comment by RPS98** [comment]
I think it's still unresolved
