### ISSUE TITLE
[as2_geozones] Create a Geozones package

### ISSUE THREAD

**Issue by javilinos** [aerostack2/aerostack2#388]
### Feature Description

Create a Geozone package that is able to define and store exclusion zones (geocaging) or inclusion zones (geofencing). It should work with gps coordinates and cartesian coordinates. 

### Implementation Considerations

- Ability to assign different kind of geozones, with a different warning message each.
- Services to create, remove, and see stored geozones.

**Comment by miferco97** [comment]
@javilinos, generate a draft PR with the merge
