### ISSUE TITLE
[as2_platform_gazebo] Gimbal payload not working

### ISSUE THREAD

**Issue by mhl787156** [aerostack2/aerostack2#443]
### ROS2 Version

humble

### Version

main

### What happened?

Just trying to add a gimbal payload, but getting a launch problem:

world.json out of the examples
```json
{
    "world_name": "empty",
    "drones": [
        {
            "model_type": "quadrotor_base",
            "model_name": "cf0",
            "xyz": [
                0.0,
                0.0,
                0.3
            ],
            "rpy": [
                0,
                0,
                0.0
            ],
            "flight_time": 60,
            "payload": [
                {
                    "model_name": "gimbal",
                    "model_type": "gimbal_speed",
                    "payload": {
                        "model_name": "hd_camera0",
                        "model_type": "hd_camera"
                    }
                }
            ]
        }
    ],
    "objects": []
}
```

Launch
```bash
> ros2 launch as2_platform_gazebo platform_gazebo_launch.py namespace:=cf0 use_sim_time:=true simulation_config_file:=sim_config/world.json 
[INFO] [launch]: All log files can be found below /home/mickey/.ros/log/2024-03-22-16-24-10-551647-mickey-delta-laptop-274309
[INFO] [launch]: Default logging verbosity is set to INFO
[CRITICAL] [launch]: <launch.substitutions.path_join_substitution.PathJoinSubstitution object at 0x77adbb40add0>
[ERROR] [launch]: Caught exception in launch (see debug for traceback): field "payload" not yet prepared so type is still a ForwardRef, you might need to call Payload.update_forward_refs().
```
I know its the gimbal payload because if I add the gps its fine. Its only when the gimbal payload is added it complains. 

I'd like to grab debug or logs but I still can't figure out the easiest way to get either in ROS2... 

Thanks!

**Comment by pariaspe** [comment]
Hi @mhl787156 , there is a known bug in the gimbal. Try to set payload gimbal name as the `model_type`. Something like this:

```json
{
    "world_name": "empty",
    "drones": [
        {
            "model_type": "quadrotor_base",
            "model_name": "cf0",
            "xyz": [
                0.0,
                0.0,
                0.3
            ],
            "rpy": [
                0,
                0,
                0.0
            ],
            "flight_time": 60,
            "payload": [
                {
                    "model_name": "gimbal",
                    "model_type": "gimbal_speed",
                    "payload": {
                        "model_name": "hd_camera",
                        "model_type": "hd_camera"
                    }
                }
            ]
        }
    ],
    "objects": []
}
```

**Comment by mhl787156** [comment]
Hi @pariaspe no dice unfortunately, same issue. 

![image](https://github.com/aerostack2/aerostack2/assets/10742598/206cae82-49a3-431f-8478-dd83a09a3f18)

Are there some logs somewhere I can grab? 

In case the gimbal doesn't work, does the camera work without being put on the gimbal? i.e. If I just want a fixed forward facing camera?

**Comment by pariaspe** [comment]
Try this config file, it works for me:
```json
{
    "world_name": "empty",
    "drones": [
        {
            "model_type": "quadrotor_base",
            "model_name": "cf0",
            "xyz": [
                0.0,
                0.0,
                0.3
            ],
            "rpy": [
                0,
                0,
                0.0
            ],
            "flight_time": 60,
            "payload": [
                {
                    "model_name": "gb",
                    "model_type": "gimbal_position",
                    "payload": {
                        "model_name": "hd_camera",
                        "model_type": "hd_camera"
                    }
                }
            ]
        }
    ]
}
```

> In case the gimbal doesn't work, does the camera work without being put on the gimbal? i.e. If I just want a fixed forward facing camera?

Sure, you don't need a gimbal then. Use a fixed position for the camera instead. Gimbals is something new we made lately but it still *under review* and you may face a bunch of bugs.

**Comment by mhl787156** [comment]
Still no luck unfortunately same problem. 

Its alright, I will remove the gimbal from now and it works fine! 

Out of interest will the camera work as a standalone object? i.e. a static camera in the scene?

**Comment by pariaspe** [comment]
Yes, it can work as a standalone object. We don't have any models with cameras attached available, but it is really easy to do

**Comment by lfletcher-turing** [comment]
> Hi @mhl787156 , there is a known bug in the gimbal. Try to set payload gimbal name as the `model_type`. Something like this:
> 
> ```json
> {
>     "world_name": "empty",
>     "drones": [
>         {
>             "model_type": "quadrotor_base",
>             "model_name": "cf0",
>             "xyz": [
>                 0.0,
>                 0.0,
>                 0.3
>             ],
>             "rpy": [
>                 0,
>                 0,
>                 0.0
>             ],
>             "flight_time": 60,
>             "payload": [
>                 {
>                     "model_name": "gimbal",
>                     "model_type": "gimbal_speed",
>                     "payload": {
>                         "model_name": "hd_camera",
>                         "model_type": "hd_camera"
>                     }
>                 }
>             ]
>         }
>     ],
>     "objects": []
> }
> ```

Does this bug mean that it is not currently possible to add more than 1 camera of the same type to a single drone?

**Comment by pariaspe** [comment]
> Does this bug mean that it is not currently possible to add more than 1 camera of the same type to a single drone?

No, you can still many cameras without using a gimbal

**Comment by lfletcher-turing** [comment]
> > Does this bug mean that it is not currently possible to add more than 1 camera of the same type to a single drone?
> 
> No, you can still many cameras without using a gimbal

Even if I don't use a gimbal, I cannot seem to get multiple cameras to work. In fact, if I don't match the model_name to the model_type, the camera stream will not work. So for example, this will work and will display in eg rviz:

```json
{
    "world_name": "empty",
    "drones": [
        {
            "model_type": "quadrotor_base",
            "model_name": "drone0",
            "xyz": [1.0, 1.0, 0.3],
            "rpy": [0, 0, 0],
            "flight_time": 60,
            "payload": [
                {
                    "model_name": "hd_camera",
                    "model_type": "hd_camera"
                }
            ]
        }
    ]   
}
```

But if I change the model_name to something else, such as "front_camera" for example, then there are no launch issues, but when I try and view the image_raw topic, nothing is displayed. 

```json
{
    "world_name": "empty",
    "drones": [
        {
            "model_type": "quadrotor_base",
            "model_name": "drone0",
            "xyz": [1.0, 1.0, 0.3],
            "rpy": [0, 0, 0],
            "flight_time": 60,
            "payload": [
                {
                    "model_name": "front_camera",
                    "model_type": "hd_camera"
                }
            ]
        }
    ]   
}

```
