### ISSUE TITLE
[as2_keyboard_teleoperation] PySimpleGUI needs registration

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#451]
### ROS2 Version

humble

### Version

main

### What happened?

When following the [keyboard teleoperation guide](https://aerostack2.github.io/_06_user_interfaces/_keyboard_teleoperation/index.html), PySimpleGUI asks for registration. Is there any specific free version?

![Screenshot from 2024-04-17 00-06-48](https://github.com/aerostack2/aerostack2/assets/57761265/d36f4307-d5c2-4a3b-bc2e-05747b3d6a5f)

**Comment by miferco97** [comment]
@RPS98 we need to force to use the pysimplegui==4.60 version

**Comment by javilinos** [comment]
force it with ``` pip install pysimplegui==4.60 ``` I will update documentation aswel

**Comment by miferco97** [comment]
Okay, link this issue in the documentation PR @javilinos

**Comment by RPS98** [comment]
Already in the documentation
