### ISSUE TITLE
[as2_motion_reference_handlers] Trajectory Motion handlers now include a header field but the message used does not contain any frame information. Maybe we should change our message type into one that contains a header

### ISSUE THREAD

**Issue by miferco97** [aerostack2/aerostack2#46]
Trajectory Motion handlers now include a header field but the message used does not contain any frame information. Maybe we should change our message type into one that contains a header

_Originally posted by @miferco97 in https://github.com/aerostack2-developers/motion_reference_handlers/pull/4#pullrequestreview-1128594065_

**Comment by RPS98** [comment]
Done with as2 msgs trajectory point
