### ISSUE TITLE
[aerostack2] How to migrate to ament_lint_auto

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#490]
### Feature Description

Guide to migrate from old test to [ament_lint_auto](https://github.com/ament/ament_lint/tree/humble).

Current aerostack2 packages that have been migrated to ament_lint_auto:
- [x] aerostack2
- [x] as2_alphanumeric_viewer
- [x] as2_behavior
- [x] as2_behaviors_motion
- [x] as2_behaviors_perception
- [x] as2_behaviors_platform
- [x] as2_behaviors_trajectory_generation
- [x] as2_behavior_tree
- [x] as2_cli
- [x] as2_core
- [x] as2_gazebo_assets
- [x] as2_gazebo_classic_assets
- [x] as2_keyboard_teleoperation
- [x] as2_motion_controller
- [x] as2_motion_reference_handlers
- [x] as2_msgs
- [x] as2_platform_gazebo
- [x] as2_platform_multirotor_simulator
- [x] as2_python_api
- [x] as2_realsense_interface
- [x] as2_state_estimator
- [x] as2_usb_camera_interface

External packages:

- [x] [as2_external_object_to_tf](https://github.com/aerostack2/as2_external_object_to_tf)
- [x] [as2_platform_pixhawk](https://github.com/aerostack2/as2_platform_pixhawk)
- [x] [as2_platform_dji_psdk](https://github.com/aerostack2/as2_platform_dji_psdk)
- [x] [as2_platform_dji_osdk](https://github.com/aerostack2/as2_platform_dji_osdk)
- [x] [as2_platform_tello](https://github.com/aerostack2/as2_platform_tello)
- [x] [as2_platform_crazyflie] (https://github.com/aerostack2/as2_platform_crazyflie) https://github.com/aerostack2/as2_platform_crazyflie/pull/4

### Implementation Considerations

Checkout the following documentation of [ament_lint_auto](https://github.com/ament/ament_lint/blob/humble/ament_lint_auto/doc/index.rst).

Follow the steps below to migrate from old test to ament_lint_auto.

**1**. In your **`package.xml`**, add:

```
<test_depend>ament_lint_auto</test_depend>
<test_depend>ament_lint_common</test_depend>
```

Optionally, you can add gtest as well:

```
<test_depend>ament_cmake_gtest</test_depend>
```

**2**. In your **`CMakeLists.txt`**, add:

```
if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
endif()
```

Optionally, you can add gtest with subdirectory `CMakeLists.txt`:

Root **`CMakeLists.txt`**:
```
if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
  add_subdirectory(tests)
endif()
```

`tests` folder **`CMakeLists.txt`**:
```
file(GLOB GTEST_SOURCE "*_gtest.cpp")

if(GTEST_SOURCE)
  find_package(ament_cmake_gtest REQUIRED)

  foreach(TEST_SOURCE ${GTEST_SOURCE})
    get_filename_component(TEST_NAME ${TEST_SOURCE} NAME_WE)

    ament_add_gtest(${PROJECT_NAME}_${TEST_NAME} ${TEST_SOURCE})
    ament_target_dependencies(${PROJECT_NAME}_${TEST_NAME} ${PROJECT_DEPENDENCIES})
    target_link_libraries(${PROJECT_NAME}_${TEST_NAME} gtest_main ${PROJECT_NAME})
  endforeach()
endif()
```

**3**. Compile your package:

```
as2 build <package_name>
```

**4**. Run the tests:

```
as2 test <package_name>
```

**_Note_**: Some tests dependencies can be found at:

https://github.com/aerostack2/aerostack2/blob/a9e580770a909bd2973f81be7616a6f9e95dcb0d/docker/humble/Dockerfile#L11-L29

**USEFUL UTILS**

**Copyright**

To add copyright to C++ and Python files, use the following command:

`ament_copyright --add-missing "Universidad Politécnica de Madrid" bsd_3clause`

**Uncrusitfy**

To reformat C++ code, use the following command:

`ament_uncrustify --reformat`

**Comment by pariaspe** [comment]
# VS Code settings

Tested on VSCode 1.89.0 and Ubuntu 22.04

## Extensions required
* `zachflower.uncrustify`
* `mine.cpplint`
* `ms-python.autopep8`
* `ms-python.pylint`

## Add to your settings file
```
// cpp
    "[cpp]": {
        "editor.defaultFormatter": "zachflower.uncrustify",
        "editor.codeActionsOnSave": {
            "source.fixAll": "explicit"
        },
        "editor.formatOnSave": true
    },
    "uncrustify.configPath.linux": "<path-to>/.uncrustify.cfg",

    // cpplint
    "cpplint.cpplintPath": "<path-to-bin>/cpplint",
    "cpplint.lineLength": 100,
    "cpplint.verbose": 0,
    "cpplint.filters": [
        // header guards are user defined
        "-build/header_guard",
        // we do allow C++11
        "-build/c++11",
        // we consider passing non-const references to be ok
        "-runtime/references",
        // we wrap open curly braces for namespaces, classes and functions
        "-whitespace/braces",
        // we don't indent keywords like public, protected and private with one space
        "-whitespace/indent",
        // we allow closing parenthesis to be on the next line
        "-whitespace/parens",
        // we allow the developer to decide about whitespace after a semicolon
        "-whitespace/semicolon",
    ],

    // python
    "[python]": {
        "editor.defaultFormatter": "ms-python.autopep8",
        "editor.formatOnSave": true,
    },
    "autopep8.args": ["--max-line-length=99", "--ignore=''"],

    // ROS2 uses as a linter flake8==4.0.1 (apt installation). Pip installation should be 
    // at the same version to avoid errors. pycodestyle==2.8.0 is also required.
    // vscode flake8 extension requires at least flake8 v5.0.0. Pylint extension is used 
    // instead with identical configuration.
    "pylint.args": ["--disable=B902,C816,D100,D101,D102,D103,D104,D105,D106,D107,D203,D212,D404,I202",
                    "--max-line-length=99", "--import-order-style=google", "--show-source=true",
                    "--statistics=true"],
```

## Uncrustify formatter configuration file
https://github.com/ament/ament_lint/blob/foxy/ament_uncrustify/ament_uncrustify/configuration/ament_code_style.cfg

## References
https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html
