### ISSUE TITLE
[as2_core] Python module with topics and service names

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#50]
Makes a python module for names services and topics. Now they are hardcode in python_interface. Should create a:
/as2_core
|--> /as2_core
      |--> __init__.py
      |--> as2_core.py

as2_core.py should have names.topic and names.services list.

Or we should move them to a new python package like "as2_python_core" ?

**Comment by miferco97** [comment]
@pariaspe this still has sense nowadays?

**Comment by pariaspe** [comment]
What about make a script to convert names.cpp into names.py?
