### ISSUE TITLE
[as2_behaviors_perception] cv::aruco::drawAxis deprecated in new version opencv

### ISSUE THREAD

**Issue by Sakura286** [aerostack2/aerostack2#508]
### ROS2 Version

humble

### Version

v1.0.9

### Installation

source

### What happened?

I am trying to build aerostack2 as2_behaviors_perception with gcc 13.2 and opencv 4.6, but the build failed with such log:

```log
/tmp/binarydeb/ros-humble-as2-behaviors-perception-1.0.9/detect_aruco_markers_behavior/src/detect_aruco_markers_behavior.cpp:194:18: error: ‘drawAxis’ is not a member of ‘cv::aruco’
  194 |       cv::aruco::drawAxis(output_image, camera_matrix_, dist_coeffs_, rout, tout, 0.08625);
      |                  ^~~~~~~~
```

cv::aruco::drawAxis has been [deprecated](https://github.com/opencv/opencv_contrib/commit/0f030dd0) on opencv-contrib 3.4.7/4.1.1 from Apri 2019 and [removed](https://github.com/opencv/opencv_contrib/commit/56d492cf) on 3.4.18/4.6.0 from Mar 17, 2022.

Need to migrate from cv::aruco::drawAxis to cv::DrawFrameAxes?

### How to reproduce your issue?

- gcc 13.2
- opencv 4.6

**Comment by pariaspe** [comment]
Fixed in #509
