### ISSUE TITLE
[as2_core] dynamic as2_names for several same type sensors

### ISSUE THREAD

**Issue by pariaspe** [aerostack2/aerostack2#52]
Two same type sensor will publish now at the same topic (`/drone_sim_0/sensor_measurements/gps`) following the current name convention.
```json
"model": "quadrotor_base",
"name": "drone_sim_0",
"payload": {
    "gps0": {
        "sensor": "gps"
    },
    "gps1": {
        "sensor": "gps"
    }
}
```
Shouldn't they publish on different topics `/drone_sim_0/sensor_measurements/{sensor_name}/gps`?

**Comment by RPS98** [comment]
Now, with as2_core sensors, users can set the sensor name. If there is more than one GPS or IMU, the user must specify in the state estimator which one to use for localization.
