### ISSUE TITLE
[aerostack2] Create a utilities package

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#528]
### Feature Description

Packages to be include:

- [ ] [as2_external_object_to_tf](https://github.com/aerostack2/as2_external_object_to_tf)
- [ ] [geozones](https://github.com/aerostack2/geozones) - #388

**Comment by javilinos** [comment]
@miferco97 is geozones package to be included? I believe it's going to be integrated in knowledge graph package soon.

**Comment by miferco97** [comment]
Yes it is going to be included, the KG implementation may use it not integrate it
