### ISSUE TITLE
How can I use the Web GUI?

### ISSUE THREAD

**Issue by Cristian-wp** [aerostack2/aerostack2#580]
Hello,
I am trying to use your package with the tutorial. For what I see on your pubblication and presentation, there is a Web GUI that can be used for path planning.

<img width="1545" alt="2024-07-08 16_06_48-Aerostack2_A_framework_for_developing_Multi-Robot_Aerial_Systems pdf - Adobe Acr" src="https://github.com/aerostack2/aerostack2/assets/61200634/15beb87b-09b2-4632-96f6-80abe8cac0ca">

How can I use it in my simulations? I can not find any reference in the repositories.

**Comment by Cristian-wp** [comment]
Any news?

**Comment by RPS98** [comment]
Hi @Cristian-wp,

We are currently working on its release for the next version of Aerostack2, so it will be available soon

**Comment by Cristian-wp** [comment]
@RPS98 can you give me an approximative release date(next month, semptember, 2025,ecc...)?

**Comment by miferco97** [comment]
During this month

**Comment by Cristian-wp** [comment]
@miferco97 Thank you for the quick reply 👍🏻  . It will be the same version with PX4+Gazebo(fortress) examples?

**Comment by RPS98** [comment]
Hi @Cristian-wp,

Checkout this documentation: https://github.com/aerostack2/as2_web_gui/issues/5
