### ISSUE TITLE
[as2_state_estimator] Transform between odom and earth with Ground Truth plugin is not as expected 

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#615]
### ROS2 Version

humble

### Version

main

### Installation

binaries

### What happened?

**Expected** TF tree:
- Earth at world origin
- Map at initial UAV pose
- Odom at initial UAV pose

When using `raw_odometry` and not GPS origin:
- Earth at initial UAV pose
- Map at initial UAV pose
- Odom at initial UAV pose

When using `raw_odometry` and GPS origin:
- Earth at GPS origin
- Map at initial UAV pose using GPS transform
- Odom at initial UAV pose using GPS transform

When using `ground_truth` and `mocap_pose`:
- Earth at world/mocap origin
- Map at initial UAV pose
- Odom at initial UAV pose

**Current** TF tree when using `ground_truth` plugin:
- Earth at world/mocap origin
- Map at world/mocap origin
- Odom at world/mocap origin

### How to reproduce your issue?

Launch project_gazebo and open rviz:

![Gazebo_tf_rviz](https://github.com/user-attachments/assets/036e966b-b609-4df0-ac0b-2c1b23b91a8e)

Drone0 starts at [0.5,0.0,0.0], but odom and map frames starts at the same point of earth frame

**Comment by RPS98** [comment]
@javilinos @miferco97 What do you think?

**Comment by miferco97** [comment]
![image](https://github.com/user-attachments/assets/88c834e3-a877-408d-9aa5-c917b8ad7d98)
It seems like the part of the code in charge of generating this transform has been commented :S

**Comment by javilinos** [comment]
When I updated the code in this [commit](https://github.com/aerostack2/aerostack2/commit/72c482fcfadcc3af3769596d0e2e31447ba7c96f#diff-5a063a1fe52022e938589eb2615e868f355cae920995294432e31194e7d4ca4b) for the map to be generated in the starting position I managed to build the transformation tree as desired. However, when testing it in simulation, controller would fail for some reason, so I reverted back in the next [commit](https://github.com/aerostack2/aerostack2/commit/7e96753300fc140d7b13d8e0c69290e2fe0d040c) (It was quite a while ago actually). In theory, only uncommenting those lines would make it right. I would test it again and see if it works as intended.

**Comment by javilinos** [comment]
As I said only by uncommenting the lines I made back in the day, it already works as expected:

![Screenshot from 2024-07-26 18-29-05](https://github.com/user-attachments/assets/0c716e28-d6fa-4a56-816b-abcee0ca33eb)

About the changes to the set_origin_on_start parameter I would open another Issue where we can discuss how we want that parameter to work/be modified
