### ISSUE TITLE
New Aerostack2 release date

### ISSUE THREAD

**Issue by Cristian-wp** [aerostack2/aerostack2#634]
Hello, there are any news or maybe a date about the new version release?

**Comment by pariaspe** [comment]
> Hello, there are any news or maybe a date about the new version release?

Hi, release is done and binaries will be available in next Humble sync (probably in one or two weeks)

**Comment by pariaspe** [comment]
Release is out!
https://discourse.ros.org/t/preparing-for-humble-sync-2024-08-28/39316/2

**Comment by Cristian-wp** [comment]
@pariaspe thank you for the reply! I have already see it, but I have not found the [Web User Interface](https://github.com/aerostack2/aerostack2/issues/580#issuecomment-2225151628) reported in your paper...If is in your new release how can I launch it?

**Comment by pariaspe** [comment]
No, it wasn't released this time. We had some difficulty packing the WUI and we had a big delay in the release, so we decided to continue without it. @RPS98 might guide you on how to source install and launch it.

**Comment by Cristian-wp** [comment]
Hi @pariaspe , thank you for your reply. I hope it will be fixed soon.
@RPS98 can you please guide me to source install the version with GUI?
