### ISSUE TITLE
[all] Include GPS Translator functions

### ISSUE THREAD

**Issue by perezsaura-david** [aerostack2/aerostack2#71]
There is a util in as2_core to convert from origin position (correspondency between GPS and Cartesian coordinates) and a drone position (in GPS or cartesian).

Node as2_state_estimator should have a service to get the origin, which is the correspondency between the GPS coordinate of the origin and the earth frame in cartesian.

For transformation, there are several posibilities:
* as2_python_api do the conversion, and send goal in earth frame.
* A motion reference with GPS coordinates, that do the conversion and send command to controller in earth.
* Motion reference with GPS send references in GPS and controller manager do the conversion.
   * Use frame_id to indicate if pose reference is in cartesian or in GPS.
   * GPS have two options:
     * Height relative to earth.
     * Height relative to amsl.

What do you thing @perezsaura-david @pariaspe @miferco97?

**Comment by miferco97** [comment]
I open a branch to work on this
